# Importando bibliotecas

In [155]:
import pandas as pd

In [156]:

# Importando dados
df_clientes = pd.read_csv('../data/raw/customers.csv')
df_products = pd.read_csv('../data/raw/products.csv')
df_stores = pd.read_csv('../data/raw/stores.csv')
df_sales = pd.read_csv('../data/raw/sales.csv')
df_items_sales = pd.read_csv('../data/raw/items_sales.csv')

In [157]:
# Unindo a tabela de produtos com a de items de vendas
df_items_sales = pd.merge(df_items_sales, df_products, on='id_product', how='inner')
df_items_sales.head()

,id_item_sale,id_sale,id_product,quantity,unity_price,discount,name,category,price,custo
0,1,1,64,1,465.77,0.00,Controle Xbox Wireless Digital,Games,465.77,377.32
1,2,2,131,2,254.41,0.00,Teclado Redragon Kumara RGB,Periféricos,254.41,191.99
2,3,2,127,2,108.37,18.76,Teclado Logitech K120 Wireless,Periféricos,108.37,80.80
3,4,2,107,1,356.54,0.00,Headset HyperX Cloud Stinger Wireless,Periféricos,356.54,236.00
4,5,2,132,3,271.63,0.00,Teclado Redragon Kumara Wireless,Periféricos,271.63,198.24

# Qual categoria de produtos teve mais lucro?

In [158]:
# Primeiro vamos criar uma nova coluna, multiplicando a quantidade pelo preco
df_items_sales['total'] = df_items_sales['quantity'] * df_items_sales['price']
df_items_sales.head()

,id_item_sale,id_sale,id_product,quantity,unity_price,discount,name,category,price,custo,total
0,1,1,64,1,465.77,0.00,Controle Xbox Wireless Digital,Games,465.77,377.32,465.77
1,2,2,131,2,254.41,0.00,Teclado Redragon Kumara RGB,Periféricos,254.41,191.99,508.82
2,3,2,127,2,108.37,18.76,Teclado Logitech K120 Wireless,Periféricos,108.37,80.80,216.74
3,4,2,107,1,356.54,0.00,Headset HyperX Cloud Stinger Wireless,Periféricos,356.54,236.00,356.54
4,5,2,132,3,271.63,0.00,Teclado Redragon Kumara Wireless,Periféricos,271.63,198.24,814.89

In [159]:
category_money = (
    df_items_sales.groupby('category')['total']
    .sum()
    .reset_index(name='total_vendas')
    .sort_values(by='total_vendas', ascending=False)
)

In [160]:
category_money

      category  total_vendas
2        Games   16730840.04
6        Áudio   15216181.54
1     Cadeiras   14048976.33
3    Monitores   13720105.45
5  Smartphones   13454794.20
0   Acessórios   10769913.45
4  Periféricos    6053278.14

Nosso maior lucro vem da categoria de games, seguido por áudio e Cadeiras.

In [161]:
# total de vendas

total_sales = category_money['total_vendas'].sum()
print(f"Nosso faturamento total foi de R$ {total_sales}")

Nosso faturamento total foi de R$ 89994089.15

In [162]:
# Vamos descobrir como as categorias representam em porcentagem para o valor final.
category_money['porcentagem'] = (category_money['total_vendas'] / total_sales) * 100
category_money['porcentagem'] = round(category_money['porcentagem'],2)
category_money

      category  total_vendas  porcentagem
2        Games   16730840.04        18.59
6        Áudio   15216181.54        16.91
1     Cadeiras   14048976.33        15.61
3    Monitores   13720105.45        15.25
5  Smartphones   13454794.20        14.95
0   Acessórios   10769913.45        11.97
4  Periféricos    6053278.14         6.73

Vamos agora descobrir o quanto gastamos para posteriormente descobrir o lucro líquido.

In [163]:
df_items_sales['custo_total'] = df_items_sales['quantity'] * df_items_sales['custo']
df_items_sales.head()

,id_item_sale,id_sale,id_product,quantity,unity_price,discount,name,category,price,custo,total,custo_total
0,1,1,64,1,465.77,0.00,Controle Xbox Wireless Digital,Games,465.77,377.32,465.77,377.32
1,2,2,131,2,254.41,0.00,Teclado Redragon Kumara RGB,Periféricos,254.41,191.99,508.82,383.98
2,3,2,127,2,108.37,18.76,Teclado Logitech K120 Wireless,Periféricos,108.37,80.80,216.74,161.60
3,4,2,107,1,356.54,0.00,Headset HyperX Cloud Stinger Wireless,Periféricos,356.54,236.00,356.54,236.00
4,5,2,132,3,271.63,0.00,Teclado Redragon Kumara Wireless,Periféricos,271.63,198.24,814.89,594.72

In [164]:
# Custo por category

custo_category_money = (
    df_items_sales.groupby('category')['custo_total']
    .sum()
    .reset_index(name='custo_total_compras')
    .sort_values(by='custo_total_compras', ascending=False)
)
custo_category_money.head()

      category  custo_total_compras
2        Games          13506069.74
6        Áudio          11684057.71
1     Cadeiras          11112166.46
5  Smartphones          10866434.24
3    Monitores          10798177.23

In [165]:
total_custo = custo_category_money['custo_total_compras'].sum()

In [166]:
faturamento_liquido_vendas = total_sales - total_custo
print(f'Nosso faturamento líquido é de R$ {faturamento_liquido_vendas}')

Nosso faturamento líquido é de R$ 19852849.560000017

# Qual loja é vende mais?

In [167]:
df_stores

    id_store                store_name                     city Country
0          1         TechStore Vitória                  Vitória  Brasil
1          2      TechStore Vila Velha               Vila Velha  Brasil
2          3           TechStore Serra                    Serra  Brasil
3          4       TechStore Cariacica                Cariacica  Brasil
4          5        TechStore Linhares                 Linhares  Brasil
5          6        TechStore Colatina                 Colatina  Brasil
6          7       TechStore Cachoeiro  Cachoeiro de Itapemirim  Brasil
7          8       TechStore São Paulo                São Paulo  Brasil
8          9        TechStore Campinas                 Campinas  Brasil
9         10          TechStore Santos                   Santos  Brasil
10        11             TechStore Rio           Rio de Janeiro  Brasil
11        12         TechStore Niterói                  Niterói  Brasil
12        13  TechStore Belo Horizonte           Belo Horizonte  Brasil
13        14        TechStore Curitiba                 Curitiba  Brasil
14        15    TechStore Porto Alegre             Porto Alegre  Brasil

In [168]:
df_sales

       id_sale  id_customer  id_store     payment_method
0            1           14        10   Cartão de Débito
1            2           15        13                PIX
2            3           86         1                PIX
3            4           71         1  Cartão de Crédito
4            5           21        13                PIX
...        ...          ...       ...                ...
49995    49996           76         5  Cartão de Crédito
49996    49997          101        12  Cartão de Crédito
49997    49998           36         7                PIX
49998    49999           36         3   Cartão de Débito
49999    50000           59        13                PIX

[50000 rows x 4 columns]

In [169]:
df_sales_store = pd.merge(df_sales, df_stores, on='id_store', how='inner')
df_sales_store.head()

,id_sale,id_customer,id_store,payment_method,store_name,city,Country
0,1,14,10,Cartão de Débito,TechStore Santos,Santos,Brasil
1,2,15,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil
2,3,86,1,PIX,TechStore Vitória,Vitória,Brasil
3,4,71,1,Cartão de Crédito,TechStore Vitória,Vitória,Brasil
4,5,21,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil

In [170]:
# Qual loja vendeu mais, por quantidade!

df_store_quantity_sales = df_sales_store.groupby('store_name').size().reset_index(name='qtd_vendas').sort_values(by='qtd_vendas',ascending=False)
df_store_quantity_sales

                  store_name  qtd_vendas
0   TechStore Belo Horizonte        3429
4         TechStore Colatina        3421
1        TechStore Cachoeiro        3417
11           TechStore Serra        3383
2         TechStore Campinas        3358
14         TechStore Vitória        3341
10          TechStore Santos        3332
12       TechStore São Paulo        3330
5         TechStore Curitiba        3319
3        TechStore Cariacica        3317
13      TechStore Vila Velha        3303
9              TechStore Rio        3294
7          TechStore Niterói        3284
8     TechStore Porto Alegre        3257
6         TechStore Linhares        3215

In [171]:
# Qual cliente comprou em mais quantidade?
df_sales_store = pd.merge(df_sales_store, df_clientes, on='id_customer', how='inner')

df_sales_store.head()

,id_sale,id_customer,id_store,payment_method,store_name,city,Country,customer_name,state,registration_date
0,1,14,10,Cartão de Débito,TechStore Santos,Santos,Brasil,Valentina Moura,PB,2026-03-21
1,2,15,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil,Enzo Gabriel Gomes,PB,2025-08-17
2,3,86,1,PIX,TechStore Vitória,Vitória,Brasil,Ana Beatriz Nunes,RJ,2025-03-09
3,4,71,1,Cartão de Crédito,TechStore Vitória,Vitória,Brasil,Stephany da Rosa,AM,2025-03-05
4,5,21,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil,Ana da Paz,RJ,2024-10-25

In [172]:

df_customer_quantity = df_sales_store.groupby('customer_name').size().reset_index(name='qtd_compras').sort_values(by='qtd_compras', ascending=False)

In [173]:
df_customer_quantity.head()

       customer_name  qtd_compras
82    Mirella Araújo          489
108     Thales Abreu          465
25    Clarice Macedo          458
84   Murilo Monteiro          458
88       Olivia Dias          455

In [175]:
df_items_sales.head()
df_geral = pd.merge(df_sales_store, df_items_sales, on='id_sale', how='inner')

In [176]:
df_geral

,id_sale,id_customer,id_store,payment_method,store_name,city,Country,customer_name,state,registration_date,...,id_product,quantity,unity_price,discount,name,category,price,custo,total,custo_total
0,1,14,10,Cartão de Débito,TechStore Santos,Santos,Brasil,Valentina Moura,PB,2026-03-21,...,64,1,465.77,0.00,Controle Xbox Wireless Digital,Games,465.77,377.32,465.77,377.32
1,2,15,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil,Enzo Gabriel Gomes,PB,2025-08-17,...,131,2,254.41,0.00,Teclado Redragon Kumara RGB,Periféricos,254.41,191.99,508.82,383.98
2,2,15,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil,Enzo Gabriel Gomes,PB,2025-08-17,...,127,2,108.37,18.76,Teclado Logitech K120 Wireless,Periféricos,108.37,80.80,216.74,161.60
3,2,15,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil,Enzo Gabriel Gomes,PB,2025-08-17,...,107,1,356.54,0.00,Headset HyperX Cloud Stinger Wireless,Periféricos,356.54,236.00,356.54,236.00
4,2,15,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil,Enzo Gabriel Gomes,PB,2025-08-17,...,132,3,271.63,0.00,Teclado Redragon Kumara Wireless,Periféricos,271.63,198.24,814.89,594.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96548,50000,59,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil,Thales Abreu,MA,2024-12-04,...,122,4,70.04,0.00,Mousepad Havit Wireless,Periféricos,70.04,52.81,280.16,211.24
96549,50000,59,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil,Thales Abreu,MA,2024-12-04,...,121,1,65.43,4.36,Mousepad Havit RGB,Periféricos,65.43,48.91,65.43,48.91
96550,50000,59,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil,Thales Abreu,MA,2024-12-04,...,112,1,213.13,7.16,Mouse Logitech G203 Wireless,Periféricos,213.13,160.61,213.13,160.61
96551,50000,59,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil,Thales Abreu,MA,2024-12-04,...,14,1,110.77,0.00,Carregador Samsung 25W Premium,Acessórios,110.77,76.47,110.77,76.47
96552,50000,59,13,PIX,TechStore Belo Horizonte,Belo Horizonte,Brasil,Thales Abreu,MA,2024-12-04,...,109,1,185.46,0.00,Mouse Logitech G203 Cinza,Periféricos,185.46,142.75,185.46,142.75

In [181]:
# QUAL METODO DE PAGAMENTO FOI MAIS UTILIZADO?
df_payment_method = df_geral.groupby('payment_method')['total'].sum().reset_index(name='value')
df_payment_method = df_payment_method.sort_values('value', ascending=False)
df_payment_method

      payment_method        value
0  Cartão de Crédito  40332722.46
3                PIX  31810916.90
1   Cartão de Débito  13464951.32
2           Dinheiro   4385498.47

KeyError: 'sale_date'